### ISSUE TITLE
Game Shutdown After Installing Ascended Upgrades

### ISSUE THREAD

**Issue by cyrus01337** [gurrenm3/BTD-Mod-Helper#115]
Unsure if this is a problem with this mod or Ascended Upgrades, upon installing it the game crashes. Upon restarting the game, the mod is installed.

This doesn't seem to be an issue with other mods and I was wondering what I could do to confirm this as it seems the terminal (for what I'm assuming is for Melon Loader to initialise prerequisites then hook into BTD6) also closes alongside the game, leaving no way to identify the issue (that I can see).

**Comment by cyrus01337** [comment]
Have confirmed with the author of Ascended Upgrades, this is a problem with the mod helper.

Any direction that can be taken/details that can be provided in order to help contribute to a solution?

**Comment by doombubbles** [comment]
The most important thing needed for a solution is reproducibility. Crashing when downloading is something that's been an intermittent bug report since the functionality was added, and I've even seen it myself, but it always ends up working again the next couple dozen times afterwards. The crashes don't give any information likely because they're related to asynchronous methods and il2cpp doesn't have a great track record on those when it comes to clarity.
