### ISSUE TITLE
Melonloader cannot find the file.

### ISSUE THREAD

**Issue by Obsidian-Prime** [gurrenm3/BTD-Mod-Helper#127]
For whatever reason, Melonloader is saying this:
![Screenshot (298)](https://user-images.githubusercontent.com/111253993/231871911-8337e260-a6e4-45c0-a98d-5ea47c44dfb1.png)

**Comment by doombubbles** [comment]
At this point 2.0.3 is a pretty ancient version of Mod Helper. If it's a specific mod you're trying to use that's requiring it, it's definitely too old to work with current BTD6. If it's actually been 2 years since you last played with mods, I'd recommend you start with a clean BloonsTD6 directory and following the [Install Guide](https://gurrenm3.github.io/BTD-Mod-Helper/wiki/Install-Guide) from scratch.

**Comment by Obsidian-Prime** [comment]
Huh, I got the older version from the link that was under the README section of the main page.
