### ISSUE TITLE
crashing on open

### ISSUE THREAD

**Issue by shnafnif** [gurrenm3/BTD-Mod-Helper#145]
[Latest.log](https://github.com/gurrenm3/BTD-Mod-Helper/files/11724995/Latest.log)

**Comment by doombubbles** [comment]
Can you screenshot your mods folder / provide a full list of mods?

**Comment by WildArticunoAppeared** [comment]
Actually, I'm gonna do the really difficult part and manually troubleshoot this since I'm having the same problem:
Mod Helper v3.1.9 does not crash without any other mods installed. So I disabled every mods and re-enabled them all one by one and... uh... nothing crashed... ...I did notice an XML file had appeared in my mods folder, though. So it could've had something to do with that.

**Comment by doombubbles** [comment]
Some people on the discord with issues similar to this have found success by deleting and redownloading the Btd6ModHelper.dll btw
