### ISSUE TITLE
Game crashes as soon as I put this mod in

### ISSUE THREAD

**Issue by ImAwEs0me** [gurrenm3/BTD-Mod-Helper#262]
![Screenshot 2024-08-31 222937](https://github.com/user-attachments/assets/3533a533-659f-431a-9152-f2991f599bae)
# Bug

**Comment by doombubbles** [comment]
https://gurrenm3.github.io/BTD-Mod-Helper/wiki/Install-Guide#missing-assembly-charpdll
MelonLoader did not install correctly, this most commonly happens because of anti virus software. You'll need to re install MelonLoader with your antivirus turned off or with exemptions made for the files that MelonLoader generates.
