### ISSUE TITLE
Btd6 Return to v33.3 is broken

### ISSUE THREAD

**Issue by KingOfAllPears** [gurrenm3/BTD-Mod-Helper#91]
When I boot up btd6 after doing all the steps it just gets stuck on the loading page. Like after it fully loads up, I press start and it gets stuck on the sun god monkey loading stage. Is this happening to everyone or is it just me?

**Comment by ForzMH** [comment]
Same over here

**Comment by KingOfAllPears** [comment]
oof. Guess we just have to wait until we get melonloader for v34

**Comment by galetonix** [comment]
same

**Comment by dropier** [comment]
i've tried downgrading to melon 0.5.5 already
probably wouldn't work even if i tried using melon 0.5.4 or lower but it's worth a shot, i'll see if it works rn

**Comment by dropier** [comment]
or maybe it's the mod versions, instead of getting the new ones i could also try using an older version of the mods i have and i'll also see if that works

**Comment by dropier** [comment]
melon 0.5.4 didn't load surprisingly any mods but still looped on the loading screen, probably normal since the version is really old

**Comment by dropier** [comment]
yeah.... unsurprisingly nothing worked. it's back to waiting boys, at least we tried

**Comment by doombubbles** [comment]
Yeah, something to clarify is that depending on how much you were already playing v34 on your account, your profile may just no longer be reconcilable with v33 anymore. There's not much to do in that case, since that's one of the main reasons they try to force people to update. This mod helper change lets people with reconcilable profiles keep playing, but just lets people without reconcilable profiles at least know that's the case rather than getting an inescapable popup.
